from pydantic import BaseModel

from intelligence_layer.core.task import Chunk


class SummarizeInput(BaseModel):
    """The input for a `Summarize` task.

    Attributes:
        chunk: The text chunk to be summarized.
    """

    chunk: Chunk


class SummarizeOutput(BaseModel):
    """The output of a `Summarize` task.

    Attributes:
        summary: The summary generated by the task.
    """

    summary: str
