# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor:
        update-types:
          - minor
          - patch
    commit-message:  # Workaround for bug https://github.com/dependabot/dependabot-core/issues/9784. Block can be removed once it's fixed
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
      include: "scope"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "daily"
    commit-message: # Workaround for bug https://github.com/dependabot/dependabot-core/issues/9784. Block can be removed once it's fixed
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/trace-viewer/"
    schedule:
      interval: "daily"
    groups:
      minor:
        update-types:
          - minor
          - patch
    commit-message: # Workaround for bug https://github.com/dependabot/dependabot-core/issues/9784. Block can be removed once it's fixed
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/trace-viewer/"
    schedule:
      interval: "daily"
    commit-message: # Workaround for bug https://github.com/dependabot/dependabot-core/issues/9784. Block can be removed once it's fixed
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
      include: "scope"
