# Until now, a push to a branch for which a MR exists would result in two CI pipelines.
# One would run the E2E tests and build the docker image, the other one would run the rust tests.
# This fixes this issue, resulting in only one pipeline.
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always

# all jobs can be interrupted, e.g. when a newer pipeline for the same branch starts
default:
  interruptible: true

stages:
  - lint-and-test
  - deploy-package

precommit-and-mypy:
  stage: lint-and-test
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate
  script:
    - mypy
    - pre-commit run --all-files
    - pytest

run-notebooks:
  stage: lint-and-test
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate
  script:
    - ./scripts/notebook_runner.sh


deploy-package:
  stage: deploy-package
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate
  script:
    - export PACKAGE_VERSION_ALPHA_VERSION_FORMAT='{version}a{distance}+{commit_hash}'
    - poetry self add poetry-git-version-plugin
    - poetry config repositories.gitlab "https://gitlab.aleph-alpha.de/api/v4/projects/$CI_PROJECT_ID/packages/pypi"
    - poetry config http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
    - poetry publish -r gitlab --build
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
