repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
        exclude: trace-viewer/
      - id: pretty-format-json
        files: .json
        args:
          - --autofix
        exclude: trace-viewer/
      - id: end-of-file-fixer
        exclude: trace-viewer/
      - id: trailing-whitespace
        exclude: trace-viewer/
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
  # https://black.readthedocs.io/en/stable/integrations/source_version_control.html#version-control-integration
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/kynan/nbstripout
    rev: 0.4.0
    hooks:
      - id: nbstripout
        files: ".ipynb"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args: ["-L", "newyorker,te,responde,ist,als,oder,technik,sie,rouge"]
        exclude: '^(poetry\.lock|trace-viewer/.*|tests/connectors/retrievers/test_document_index_retriever\.py|src/intelligence_layer/use_cases/qa/multiple_chunk_qa.py|src/intelligence_layer/use_cases/summarize/.*|tests/connectors/retrievers/test_document_index_retriever\.py|src/intelligence_layer/use_cases/classify/keyword_extract.py|tests/use_cases/summarize/test_single_chunk_few_shot_summarize.py|tests/use_cases/summarize/very_long_text.txt)$'
