repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        files: .json
        args:
          - --autofix
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.3
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff-lint
        args: [--fix]
        types_or: [python, pyi, jupyter]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        files: ".ipynb"
        args:
          [
            --drop-empty-cells,
            --extra-keys=metadata.kernelspec metadata.language_info.codemirror_mode.version metadata.language_info.pygments_lexer metadata.language_info.version,
          ]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          [
            "-L",
            "newyorker,te,responde,ist,als,oder,technik,sie,rouge,unter,juli,fiel,couldn,mke, vor,fille,ans",
          ]
        exclude: '^(poetry\.lock|tests/.*|src/intelligence_layer/examples/qa/multiple_chunk_qa.py|src/intelligence_layer/examples/summarize/.*|src/intelligence_layer/examples/classify/keyword_extract.py|src/intelligence_layer/learning/enrich.py)$'
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.5.9
    hooks:
      - id: pydoclint
