version: "3"
services:
  argilla-elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
  argilla:
    image: argilla/argilla-server:v1.26.1
    ports:
      - "6900:6900"
    environment:
      ARGILLA_ELASTICSEARCH: "http://argilla-elastic-search:9200"
      ARGILLA_ENABLE_TELEMETRY: 0
  open-telemetry-trace-service:
    container_name: jaeger_1_35
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    image: jaegertracing/all-in-one:1.35
  # TODO: Below code should be enabled once the secret has been added to the CI. After that, also check tests in test_tracer.py
  # export GITHUB_TOKEN=...
  # echo $GITHUB_TOKEN | docker login ghcr.io -u your_email@for_github --password-stdin
  # trace_viewer:
  #   image: ghcr.io/aleph-alpha/trace-viewer-trace-viewer:main
  #   ports:
  #    - 3000:3000
