version: "3"
services:
  argilla-elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
    command: ["elasticsearch", "-Elogger.level=ERROR"]
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
  argilla:
    depends_on:
      argilla-elastic-search:
        condition: service_healthy
    image: argilla/argilla-server:v1.29.0
    ports:
      - "6900:6900"
    environment:
      ARGILLA_ELASTICSEARCH: "http://argilla-elastic-search:9200"
      ARGILLA_ENABLE_TELEMETRY: 0
  open-telemetry-trace-service:
    container_name: jaeger_1_35
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    image: jaegertracing/all-in-one:1.35
  # export GITHUB_TOKEN=...
  # echo $GITHUB_TOKEN | docker login ghcr.io -u your_email@for_github --password-stdin
  # docker compose pull to update containers
  trace_viewer:
    image: ghcr.io/aleph-alpha/trace-viewer-trace-viewer:main
    ports:
     - 5173:3000
