[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "intelligence-layer"
version = "0.1.0"
description = ""
authors = ["Aleph Alpha Engineering <engineering@aleph-alpha.com>"]
readme = "README.md"
license = "Aleph Alpha Licensed"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pydantic = "*"
fastapi = "*"
uvicorn = "*"
aleph-alpha-client = "*"
python-dotenv = "*"
semantic-text-splitter = "^0.2.3"
qdrant-client = "^1.6.0"

[tool.poetry.group.dev.dependencies]
pytest = "*"
black = "*"
mypy = "*"
pre-commit = "*"
httpx = "*"
types-Pygments="*"
types-colorama="*"
types-docutils="*"
types-setuptools="*"
jupyterlab = "*"
types-decorator = "*"

[tool.mypy]
files = "src,tests"
strict = "True"

[tool.pytest.ini_options]
addopts = "--capture=tee-sys"
