[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "intelligence-layer"
version = "5.0.3"
description = ""
authors = ["Aleph Alpha Engineering <engineering@aleph-alpha.com>"]
readme = "README.md"
license = "Aleph Alpha Licensed"
packages = [{ include = "intelligence_layer", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pydantic = "2.8.*"
aleph-alpha-client = ">=7.1.0"
python-dotenv = "*"
semantic-text-splitter = "^0.14.1"
qdrant-client = "^1.10.1"
rich = "^13.7.1"
datasets = "^2.20.0"
requests = "^2.32.3"
pycountry = "24.6.1"
opentelemetry-api = "^1.22.0"
opentelemetry-sdk = "^1.22.0"
huggingface-hub = "^0.24.5"
opentelemetry-exporter-otlp-proto-http = "1.23.0"
# summary grader
rouge-score = "^0.1.2"
sacrebleu = "^2.4.2"
lingua-language-detector = "^2.0.2"
argilla = "^1.29.1"

[tool.poetry.group.dev.dependencies]
# lint & format
mypy = "^1.11.1"
nbqa = "^1.8.7"
ruff = "^0.5.7"
pre-commit = "^3.8.0"

# tests
pytest = "^8.3"
pytest-xdist = "^3.6.1"
nbconvert = "^7.16.4"

# typing
httpx = "*"
types-Pygments = "*"
types-colorama = "*"
types-docutils = "*"
types-setuptools = "*"
types-decorator = "*"
types-requests = "*"
types-tqdm = "*"
pandas-stubs = "^2.2.2.240807"

# docs
sphinx-rtd-theme = "^2.0.0"
sphinx = "^7.4.7"
matplotlib = "^3.9.1"

[tool.poetry.group.docs.dependencies]
fastapi = "^0.112.0"
uvicorn = "^0.30.5"
hypercorn = "^0.17.3"
jupyter = "^1.0.0"

# [tool.poetry.extras]
# argilla = ["argilla"]
# grader = ["rouge-score", "sacrebleu"]
# language-detection = ["lingua-language-detector", "pycountry"]


[tool.mypy]
files = "src,tests"
strict = "True"

[tool.pytest.ini_options]
markers = [
    "internal: marks tests as internal (deselect with '-k \"not internal\"')",
    "docker: the test depends on having a docker container running.",
]
addopts = "--capture=tee-sys"
filterwarnings = [ #ignore: message : warning : location ?
    'ignore:.*\`general_plain_validator_function\` is deprecated.*',
    'ignore::DeprecationWarning:.*importlib._bootstrap.*',
    'ignore:.*DefaultArgillaClient.*:DeprecationWarning:'
]

[tool.ruff]
target-version = "py310"
extend-include = ["*.ipynb"]

[tool.ruff.lint]
# defaults: ["E4", "E7", "E9", "F"]
# check https://docs.astral.sh/ruff/rules/ for more info
select = [
    "E4", "E7", "E9",
    "F",
    "W",
    # isort
    "I",
    # simplify
    "SIM",
    # pathlib, small but may be nice
    "PTH",
    # update to newer python versions (mostly typing)
    "UP",
    # ruff dependent checks
    "RUF",
    # bugbear
    "B",
    # pydocstring
    "D"


]
# Did not seem so useful: PD, T20(not yet), C90(eventually), PT (too opinionated)
ignore = [
    # Line too long
    "E501",
    # X | Y for hinting over optional
    "UP007",
    # unusual unicodes, next() instead of [0]
    "RUF001", "RUF015",
    # warnings should be self explanatory
    "B028",
    # we do not docstring everything
    "D1",
]
extend-safe-fixes = ["D415"]

[tool.ruff.lint.isort]
known-first-party = ["intelligence_layer", "documentation"]

[tool.ruff.lint.pydocstyle]
convention = "google"
