[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "intelligence-layer"
version = "0.8.1"
description = ""
authors = ["Aleph Alpha Engineering <engineering@aleph-alpha.com>"]
readme = "README.md"
license = "Aleph Alpha Licensed"
packages = [{ include = "intelligence_layer", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pydantic = ">=2.0"
fastapi = "*"
uvicorn = "*"
aleph-alpha-client = ">=4.0.0"
python-dotenv = "*"
semantic-text-splitter = "^0.10.0"
qdrant-client = "^1.8.2"
rich = "^13.7.1"
nbconvert = "^7.16.3"
datasets = "^2.18.0"
jupyter = "^1.0.0"
requests = "^2.31.0"
langdetect = "^1.0.9"
nltk = "^3.8.1"
pycountry = "23.12.11"
rouge = "^1.0.1"
opentelemetry-api = "^1.22.0"
opentelemetry-sdk = "^1.22.0"
huggingface-hub = "^0.22.2"
opentelemetry-exporter-otlp-proto-http = "1.23.0"

[tool.poetry.group.dev.dependencies]
# lint & format
mypy = "^1.9.0"
nbqa = "^1.8.5"
ruff = "^0.3.5"
pre-commit = "*"
pylama = { extras = ["radon", "vulture", "toml"], version = "^8.4.1" }
faker = "^24.7.1"

# tests
pytest = "*"
pytest-xdist = "^3.5.0"
hypercorn = "0.16.0"

# typing
httpx = "*"
types-Pygments = "*"
types-colorama = "*"
types-docutils = "*"
types-setuptools = "*"
types-decorator = "*"
types-requests = "*"
types-tqdm = "*"
pandas-stubs = "^2.2.1.240316"
# docs
sphinx-rtd-theme = "^2.0.0"
sphinx = "^7.2.6"
matplotlib = "^3.8.4"

[tool.mypy]
files = "src,tests"
strict = "True"

[tool.pytest.ini_options]
markers = [
    "internal: marks tests as internal (deselect with '-k \"not internal\"')",
    "docker: the test depends on having a docker container running."
]
addopts = "--capture=tee-sys"
filterwarnings = [
    'ignore:.*\`general_plain_validator_function\` is deprecated.*',
]

[tool.pylama]
skip = "*/__init__.py,.venv/*,*/node_modules/*"
ignore = "E501,E203"

[tool.ruff]
extend-include = ["*.ipynb"]

[tool.ruff.lint.mccabe]
max-complexity = 11

# we double check this, maybe pylama isn't necessary anymore
[tool.pylama.linter.mccabe]
max-complexity = "11"

[tool.isort]
profile = "black"
