[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "intelligence-layer"
version = "0.1.0"
description = ""
authors = ["Aleph Alpha Engineering <engineering@aleph-alpha.com>"]
readme = "README.md"
license = "Aleph Alpha Licensed"
packages = [{include = "intelligence_layer", from="src"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pydantic = "*"
fastapi = "*"
uvicorn = "*"
aleph-alpha-client = ">=4.0.0"
python-dotenv = "*"
semantic-text-splitter = "^0.2.3"
qdrant-client = "^1.6.0"
rich = "^13.6.0"
nbconvert = "^7.9.2"
datasets = "^2.14.5"
jupyter = "^1.0.0"
requests = "^2.31.0"
pytest-xdist = "^3.3.1"

[tool.poetry.group.dev.dependencies]
pytest = "*"
mypy = "*"
black = "*"
pre-commit = "*"
httpx = "*"
types-Pygments="*"
types-colorama="*"
types-docutils="*"
types-setuptools="*"
types-decorator = "*"
types-requests = "*"
types-tqdm = "*"

[tool.mypy]
files = "src,tests"
strict = "True"

[tool.pytest.ini_options]
markers = ["internal: marks tests as internal (deselect with '-k \"not internal\"')"]
addopts = "--capture=tee-sys -k 'not internal'"
