[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "intelligence-layer"
version = "0.5.1"
description = ""
authors = ["Aleph Alpha Engineering <engineering@aleph-alpha.com>"]
readme = "README.md"
license = "Aleph Alpha Licensed"
packages = [{include = "intelligence_layer", from="src"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pydantic = "*"
fastapi = "*"
uvicorn = "*"
aleph-alpha-client = ">=4.0.0"
python-dotenv = "*"
semantic-text-splitter = "^0.6.0"
qdrant-client = "^1.7.0"
rich = "^13.6.0"
nbconvert = "^7.14.2"
datasets = "^2.16.1"
jupyter = "^1.0.0"
requests = "^2.31.0"
pytest-xdist = "^3.5.0"
langdetect = "^1.0.9"
nltk = "^3.8.1"
pycountry = "23.12.11" #22.3.5 crushes the readthedocs
rouge = "^1.0.1"
opentelemetry-api = "^1.22.0"
opentelemetry-sdk = "^1.22.0"
huggingface-hub = "^0.20.2"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
pytest = "*"
black = "*"
pre-commit = "*"
httpx = "*"
types-Pygments="*"
types-colorama="*"
types-docutils="*"
types-setuptools="*"
types-decorator = "*"
types-requests = "*"
types-tqdm = "*"
sphinx-rtd-theme = "^2.0.0"
sphinx = "^7.2.6"
pylama = {extras = ["all"], version = "^8.4.1"}
faker = "^22.4.0"

[tool.mypy]
files = "src,tests"
strict = "True"

[tool.pytest.ini_options]
markers = ["internal: marks tests as internal (deselect with '-k \"not internal\"')"]
addopts = "--capture=tee-sys"
filterwarnings = [ 'ignore:.*\`general_plain_validator_function\` is deprecated.*' ]

[tool.pylama]
skip = "*/__init__.py,.venv/*"
ignore = "E501,E203"

[tool.pylama.linter.mccabe]
max-complexity = "11"
