[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "intelligence-layer"
version = "0.1.0"
description = ""
authors = ["Aleph Alpha Engineering <engineering@aleph-alpha.com>"]
readme = "README.md"
license = "Aleph Alpha Licensed"
packages = [{include = "intelligence_layer", from="src"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pydantic = "*"
fastapi = "*"
uvicorn = "*"
aleph-alpha-client = ">=4.0.0"
python-dotenv = "*"
semantic-text-splitter = "^0.2.3"
qdrant-client = "^1.6.0"
rich = "^13.6.0"
nbconvert = "^7.9.2"
datasets = "^2.14.5"
jupyter = "^1.0.0"
requests = "^2.31.0"
pytest-xdist = "^3.3.1"
langdetect = "^1.0.9"
nltk = "^3.8.1"
iso639-lang = "^2.1.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.6.1"
pytest = "*"
black = "*"
pre-commit = "*"
httpx = "*"
types-Pygments="*"
types-colorama="*"
types-docutils="*"
types-setuptools="*"
types-decorator = "*"
types-requests = "*"
types-tqdm = "*"
sphinx = "^7.2.6"
sphinx-rtd-theme = "^1.3.0"
pylama = {extras = ["all"], version = "^8.4.1"}

[tool.mypy]
files = "src,tests"
strict = "True"

[tool.pytest.ini_options]
markers = ["internal: marks tests as internal (deselect with '-k \"not internal\"')"]
addopts = "--capture=tee-sys"
filterwarnings = [ 'ignore:.*\`general_plain_validator_function\` is deprecated.*' ]

[tool.pylama]
skip = "*/__init__.py,.venv/*"
ignore = "E501,E203"

[tool.pylama.linter.mccabe]
max-complexity = "11"
