receivers:
  otlp:
    protocols:
      http:
        endpoint: http://localhost:4318
processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: http://localhost:8000
    encoding: json
    compression: none

service:
  pipelines:
    traces/dev:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
