name: CI

on:
  #temporary
  push:
    paths-ignore:
      - "trace-viewer/**"
      - ".github/workflows/frontend.yml"
  workflow_dispatch:
# Scheduled workflows will only run on the default branch.
  schedule:
    - cron: '0 0 * * *' # runs once a day at midnight in the timezone of your GitHub repository

jobs:
  os-support:
    uses: ./.github/workflows/sdk-tests.yml
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    with:
      runner: ${{ matrix.os }}
    secrets: inherit