on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"
      timeout:
        type: number
        default: 15 # mins

defaults:
  run:
    shell: bash

jobs:
  document-index-notebooks:
    timeout-minutes: ${{inputs.timeout}}
    runs-on: ${{inputs.runner}}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - uses: ./.github/composites/python-setup

      - name: Run Notebooks
        env:
          AA_TOKEN: ${{ secrets.AA_TOKEN }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          DOCUMENT_INDEX_URL: ${{secrets.DOCUMENT_INDEX_URL}}
        run: |
          ./scripts/notebook_runner_document_index.sh
  document-index-tests:
    timeout-minutes: ${{inputs.timeout}}
    runs-on: ${{inputs.runner}}
    continue-on-error: true
    env:
      DOCUMENT_INDEX_URL: ${{secrets.DOCUMENT_INDEX_URL}}
      AA_TOKEN: ${{ secrets.AA_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - uses: ./.github/composites/python-setup
      - name: Run client tests
        run: |
          TQDM_DISABLE=1 poetry run pytest -m "document_index and not asyncio"
      - name: Run async client tests
        run: |
          TQDM_DISABLE=1 poetry run pytest -m "document_index and asyncio"
