name: Frontend

on:
  push:
    branches:
      - main
    paths:
      - "log-viewer/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    paths:
      - "log-viewer/**"
      - ".github/workflows/frontend.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: log-viewer

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "./log-viewer/pnpm-lock.yaml"
      - run: pnpm install
      - run: pnpm check
      - run: pnpm lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "./log-viewer/pnpm-lock.yaml"
      - run: pnpm install
      - run: pnpm exec playwright install --with-deps
      - run: pnpm test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
