name: CI Pipeline

on:
  push:
    paths-ignore:
      - "trace-viewer/**"
      - ".github/workflows/frontend.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  doctest:
    uses: ./.github/workflows/doctest.yml
    secrets: inherit
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  run-notebooks:
    uses: ./.github/workflows/run_notebooks.yml
    secrets: inherit
