name: CI Pipeline

# Trigger the workflow on push
on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1

    - name: Run precommit, mypy, and pytest
      run: |
        poetry shell
        ./scripts/precommit-and-mypy-and-pytest.sh

    - name: Configure Poetry for notebooks and run
      run: |
        poetry config installer.max-workers 10
        source $(poetry env info --path)/bin/activate
        ./scripts/notebook_runner.sh
