name: Intelligence Layer SDK Tests

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  python-tests:
    uses: ./.github/workflows/sdk-tests.yml
    with:
      runner: 'ubuntu-latest'
    secrets: inherit
