name: Intelligence Layer SDK Tests

on:
  push:
    branches:
      - main
  # By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened
  pull_request:
  # manual trigger
  workflow_dispatch:



concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  python-tests:
    uses: ./.github/workflows/sdk-tests.yml
    with:
      runner: 'ubuntu-latest'
    secrets: inherit
